version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.10
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: "@theholocron/browserslist-config"
    versions:
    - 0.1.12
    - 0.1.13
  - dependency-name: npm-registry-fetch
    versions:
    - 4.0.7
    - 9.0.0
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: npm
    versions:
    - 6.14.11
    - 6.14.12
    - 6.14.13
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: "@theholocron/commitlint-config"
    versions:
    - 0.1.11
  - dependency-name: "@hidoo/sassdoc-to-markdown"
    versions:
    - 0.4.2
  - dependency-name: "@theholocron/semantic-release-config"
    versions:
    - 0.2.4
  - dependency-name: "@theholocron/stylelint-config"
    versions:
    - 0.4.0
